name: Combine XML Files

on:
  push:
    branches:
      - main # Or your default branch name
    paths:
      - '**.xml'
      - '!.github/**'
      - '!all.xml'

permissions:
  contents: write

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Concatenate XML files
        run: |
          # Create or clear the all.xml file
          > all.xml
          # Find all XML files (excluding all.xml itself) and append their full content to all.xml
          for file in $(find . -type f -name "*.xml" ! -name "all.xml"); do
            cat "$file" >> all.xml
          done

      - name: Commit and push if it changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated: Concatenated XML files"
          file_pattern: all.xml
